import type { Metadata } from 'next'
import { Akshar } from 'next/font/google'
import './globals.css'

const inter = Akshar({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App 2',
  description: 'Generated by create next app',
}

// export const viewport: Viewport = {
//   width: 'device-width',
//   // initialScale: 1,
//   minimumScale: 1,
//   // userScalable: false,
//   // viewportFit?: 'auto' | 'cover' | 'contain';
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
